### ISSUE TITLE
how can i get pid from metrics

### ISSUE THREAD

**Issue by yinbucheng** [ncabatoff/process-exporter#107]
i deploy many java programmer ,the process-export monitor record groupname all name "java" ,so  how can i Distinguish which is kafka or normal java programmer。

**Comment by taintedkernel** [comment]
I would also like the PID available as a label, for similar reasons.  If it's not available already, I may try to add support on my end.

**Comment by ncabatoff** [comment]
To distinguish multiple java processes you probably want to write a regexp based on this arguments, see #97 for an example.

The use of a pid as a label is an antipattern that this project strives to avoid, because it will result in high-cardinality metrics which Prometheus doesn't handle well.

**Comment by juliusv** [comment]
@ncabatoff In the course of my freelancing I've recently encountered two clients who would be interested in per-PID exposure as well, and I think they have use cases where it would make sense: they would only select certain long-lived processes that they want to get information on individually. Currently (in lieu of this feature) one of them is distinguishing individual processes into groups by minimal variations in Java command-line flags, but that is very brittle, especially if command-line flags might change outside of the operator's control.

What do you think of at least optionally supporting per-PID grouping?

/cc @GreenRover

**Comment by ncabatoff** [comment]
Hi @juliusv,

I've been slowly worn down as people continue to request this feature, and you adding your voice is the straw that broke the camel's back.  I can hardly refuse you this small thing after all Prometheus has done for me over the years!

I'd probably implement this as another template option that can be used to build a group name.  Odds are I wouldn't get around to it until the holidays, but of course I'm open to PRs if that's not soon enough.

**Comment by juliusv** [comment]
@ncabatoff Haha, thanks Nick! I don't want to convince people by sheer authority, as I can also be unreflected sometimes, and happy to be challenged ;) But yeah, as dangerous as PID exposure would be by default, there seem to be (in my mind) legitimate use cases for it in certain environments. Another template option to build the group name sounds good. I guess adding a dedicated `pid` label would not fit in too well with the existing concepts? Otherwise that would also be good.

I'll see whether anyone is interested in having me build it before you would get to it.

**Comment by ncabatoff** [comment]
Oh, I didn't mean to say "Because Julius says I should do it and he's an authority I'll do it".  It's more "because I appreciate what Julius has done in the past, and I was already on the fence about it, I'll do it."  I was always aware that this feature has its use cases, I just was hesitant.

Adding a dedicated `pid` label isn't out of the question.  Using the groupname template is the easiest option because it won't require changing how grouping is done.  We could also provide a pid label, though I'm not sure what benefit it would add, unless you mean instead of doing it via the template.  In which case I'm open to the idea but that's probably not how I'll do it if I implement it.

**Comment by juliusv** [comment]
@ncabatoff Yeah, going for just another template option and having it in the groupname is fine. It'd be a bit cleaner to have it in its own label, but you're right that there's no actual great upside to it.
