### ISSUE TITLE
[feature request] Add maximum open file descriptors limit

### ISSUE THREAD

**Issue by lleontop** [ncabatoff/process-exporter#11]
Hi,

Thanks for this great exporter! I was wondering if it would be possible to add the maximum open file descriptors limit per tracked process so as to be used together with open fds and alert on the 2 metrics. 
Unfortunately, I am not very familiar with go exporters but from an investigation, something similar is implemented in other exporters for monitoring its own fds like https://github.com/prometheus/memcached_exporter/blob/69ad29b59bf4a790785061094a5f1bb0112aec77/vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
```
if limits, err := p.NewLimits(); err == nil {
	c.maxFDs.Set(float64(limits.OpenFiles))
	ch <- c.maxFDs
}
```
I would appreciate this addition! Thank you!

**Comment by ncabatoff** [comment]
I've thought about adding this functionality before.  The complication (as I expound on in https://github.com/ncabatoff/process-exporter/pull/3) is that since we're tracking process *groups*, not individual processes, how do we usefully represent the limits as an aggregate?  For open FDs, we can just sum, but if you sum all the FD limits that doesn't give you much sense as to how close any individual procs in the group are getting to their limit.   I'll look into adding the worstFdRatio metric I discussed in that PR soon.

**Comment by ncabatoff** [comment]
I've pushed a lightly tested implementation of worstFdRatio.  I don't have time to build a new release right now but I'll try to get one out soon.

**Comment by lleontop** [comment]
Thank you for the fast support! I build it locally and it seems to work! Though when tracking a single process or processes of the same exe/comm, it does makes sense to report maxFDs right (and the maxFDs will be the same as the first process of the group correct)? Thank you again!

**Comment by ncabatoff** [comment]
Sure, it would make sense if you knew that you'd never have more than a single process in a group.  I don't understand the rest of your question, i.e. the "or process of the same exe/comm" anad the "maxFDs will be the same as the first process of the group".  There's no well defined "first" process in a group in the context of process-exporter.  Anyway I think it's moot since I don't plan to add a maxFD metric, I'd like all metrics to be applicable for any groups monitored.

I'll close this issue once I've updated the docs and created a release containing it.
