### ISSUE TITLE
Alert rules about process

### ISSUE THREAD

**Issue by xuanyuanaosheng** [ncabatoff/process-exporter#145]
Could you please help to provide some alert rules like: https://awesome-prometheus-alerts.grep.to/rules.html

**Comment by jinjin123** [comment]
no guys can help ...?

**Comment by ncabatoff** [comment]
Hi @xuanyuanaosheng,

I'm not sure alert rules make sense here.  Process exporter is so general that I'm having trouble thinking of any alerts that would be applicable to all users.  My alerting philosophy is that alerts should be actionable, meaning that they don't just report things that look weird, but rather should only fire when something has gone wrong and there's some manual action an operator must take.  I can't imagine what such an alert would look like for a generic process monitoring tool.

I'm going to close this issue, because I think any alert rules people come up with are going to be specific to their use cases, and not suitable for packaging with process-exporter itself.
