### ISSUE TITLE
cpu statistics: add dimentions with mode="user|system" insetead of separate counter names?

### ISSUE THREAD

**Issue by flixr** [ncabatoff/process-exporter#21]
The cpu metrics were recently split from `namedprocess_namegroup_cpu_seconds_total` into `namedprocess_namegroup_cpu_user_seconds_total` and `namedprocess_namegroup_cpu_system_seconds_total`.
I'm wondering if it wouldn't be nicer to expose them under the old name and add an extra dimension with `mode` instead (basically like the node_exporter).
Then it would be backwards compatible and easier to extend if we wanted to expose other "modes" later as well...

**Comment by ncabatoff** [comment]
The only other modes exposed by the kernel on a per-process basis that I can see in proc(5)  are guest_time and cguest_time, which I don't really see a compelling use case for.

In terms of backwards compatibility I prefer to drop metrics rather than change their labelsets.  I don't like having metrics in Prometheus with a variable number of labels.

I do agree that it would be nicer to have user/system as labels of a metric rather than distinct metrics as they are now, just so you can sum() them.  Now I just have to think of a new name for it...

**Comment by flixr** [comment]
There are also `cutime` and `cstime`, not really sure how useful they are though...

**Comment by ncabatoff** [comment]
Fixed in #84.
