### ISSUE TITLE
Provide Ubuntu .deb packages

### ISSUE THREAD

**Issue by thaniri** [ncabatoff/process-exporter#26]
## The problem:
When I run the command via BASH command line:
`./process-exporter --web.listen-address=:39256 --procnames=bash`
The process exporter works fine and provides information about the bash process.

However, when I have a SYSTEMD file on Ubuntu 16.04:
```
[Unit]
Description=Prometheus process-exporter
Wants=basic.target
After=basic.target network.target

[Service]
EnvironmentFile=/etc/environment
User=process_exporter
Group=prometheus
ExecStart=/usr/local/bin/process-exporter \
--web.listen-address=:39256 \
--procnames=bash

ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```
The process starts but it fails to report any information about the bash process (or any other process specified for that matter)

## How to replicate:
Put the process-exporter binary into `/usr/local/bin` and execute it with the same command found above.
Then create a Systemd init script and copy paste the above code block. `systemctl daemon-reload` and `service process-exporter start`

## Resolution attempts:
1. Tried to use a config file argument, the config file argument gets ignored both on the command line and through systemd.
2. Tried to not user the web.listen-address flag. 
3. Tried to change which procnames to mine for.

**Comment by thaniri** [comment]
## Resolution To -procnames Argument
Turns out the service needs to be run as root to read from /proc.

## Further issues
The exporter still refuses to read from a config file. Despite running as root.

**Comment by ncabatoff** [comment]
Can you post your new systemd unit file, the output from systemctl status process-exporter, and what exactly you mean by "refuses to read from a config file?"

**Comment by w0rd-driven** [comment]
Here's the file I'm using that seems to be working as expected:
```
[Unit]
Description=Process Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=process-exporter
Type=simple
ExecStart=/usr/local/bin/process-exporter --config.path /etc/prometheus/process-exporter.yml --web.listen-address=127.0.0.1:9915
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

I don't know pretty much anything about systemd to know if any of this is right, I cobbled it together from your example and the example given for like node_exporter that I've just used for pretty much all the go microservices related to prometheus.

Some notable changes are I'm not using the EnvironmentFile variable at all and instead of ExecStart with `\` to split up the long command line arguments, I just made it all on one line. I'm also using --config.path vs one dash though I doubt that really matters. Running it as root means it should have access to /etc/prometheus/process-exporter.yml.

`process-exporter.yml` is just in capture everything mode at the moment because I want to know all of the processes before I whitelist the important ones:
```
process_names:
  - cmdline:
    - .+
```

I'd love to know a way to have a normal user have read-only access to /proc as this feels like a security risk but I'm in a prototyping stage so it isn't terribly important yet. I think also binding to localhost and securing the crap out of the server should prevent a normal user from possibly gaining root access through this but I'm not incredibly versed in security principles to know if it's as safe as I hope.

Hopefully the issue has been solved but I mainly wanted to put this here in the event someone like me looks for a way to get this configured using systemd. This issue was already a great resource, so thanks for the input.

**Comment by ncabatoff** [comment]
I'm re-purposing this issue as a feature request to provide Ubuntu packages for process-exporter (with systemd integration).  I'll probably use your file as inspiration, thanks!

**Comment by ncabatoff** [comment]
Releases now include .deb and .rpm packages.  They should work with any Debian or Redhat based system with systemd, though they've only been tested on Ubuntu 16.04 and Centos 7.2.

**Comment by thaniri** [comment]
Thanks ncabatoff. I will do testing tonight with the new packages and tell you my results
