### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by nevmerzhitsky** [ncabatoff/process-exporter#32]
Hi, guys!

Can you describe a plan for a new release? Our team required for #17 but it was merged to `master` only still.

The last release was on 16 Nov 2016 and we don't understand can we use `master` in production with the required feature or should wait until next release will ship?

**Comment by ncabatoff** [comment]
You're right, I'm extremely overdue for a new release.  I'll get one out by tomorrow latest.

**Comment by nartzis** [comment]
Hi, @ncabatoff
What are your plans for the new release?
Will it be in the coming weeks?

**Comment by w0rd-driven** [comment]
It looks like the release dropped 19 days ago but I'm a little too much of a n00b to compile my target, linux-amd64. It'd be awesome if those were dropped in too, to save the step. It looks like the move from promu to gorelease possibly should've addressed this but I'm not exactly sure if something else would kick that off properly.

**Comment by ncabatoff** [comment]
@w0rd-driven I'm confused by your statement because the 2.1 draft release you're referring to did have linux-amd64 among the targets it built.  Anyway, I've now built an official 2.4 release, please give it a try.

All releases will now be done via goreleaser running on TravisCI, so hopefully the results should be both more reliable and more timely.  Sorry for all the delays.

**Comment by w0rd-driven** [comment]
I was going by https://github.com/ncabatoff/process-exporter/releases/tag/v0.2.1 which didn't seem to have anything linked at the time other than the source. More current releases seem to have the assets I were expecting so thanks for that and sorry if any of it was confusing. It's easily possible I didn't know where to find the other targets but it was trivial to find an earlier build.
