### ISSUE TITLE
Please reconsider the ability to disable thread level metrics.

### ISSUE THREAD

**Issue by ickymettle** [ncabatoff/process-exporter#67]
Hi, first up thanks so much for process-exporter we use it really heavily. Unfortunately for the production systems we monitor with process exporter we need the ability to disable the collection of per-thread metrics.

One of the key processes we monitor with process-exporter has anywhere from 200-300k threads on a good day, the overhead of collecting these is excessive and renders the latest release of process-exporter essentially useless for the task we use it for.

Would it be possible for the change to remove the ability to disable thread metric collection be reverted?

**Comment by ncabatoff** [comment]
Hi @ickymettle,

I was afraid that there might be a user out there like you, but I took a chance because the state metrics are essentially meaningless without the thread info.  I'm sorry to have broken behaviour you depend on.  I will find a way to accommodate both our needs - probably something close to a revert of the change, but making the current behaviour be the default and the one you desire be opt-in with a -no-threads option.
