### ISSUE TITLE
error readnig metrics (/proc/<pid>/limits)

### ISSUE THREAD

**Issue by mozai** [ncabatoff/process-exporter#76]
( I can't tell which version of process-exporter I'm using.  Can I provoke process-exporter into telling me it's own version number?  GNU utilities usually start logfile output by uttering its version number, or I can ask it by running "cmdname --version")

I'm using Linux 4.9.0-4, the  /proc/<pid>/limits files have four columns: Limit (name), Soft Limit, Hard Limit, Units.  But process-exporter is confounded trying to parse three of the columns including whitespace as one string-to-integer:

```
Limit                     Soft Limit           Hard Limit           Units     
Max processes             128629               128629               processes 
Max open files            1024                 4096                 files     
Max locked memory         18446744073708503040 18446744073708503040 bytes     
Max address space         unlimited            unlimited            bytes     
```
then
`error reading metrics for {Pid:690 StartTimeRel:989}: couldn't parse value 18446744073708503040 18446744073708503040 bytes: strconv.ParseInt: parsing "18446744073708503040 18446744073708503040 bytes": invalid syntax`

**Comment by ncabatoff** [comment]
Hi @mozai,

Unfortunately there's no good way currently to get the version out of a process-exporter binary.  It shouldn't be hard to add that though, so I'll do that going forward.

As to your limits problem: I don't know what version that was fixed in, but I believe at a minimum 0.2.0 included the fix judging by some test data that was introduced around that time.

I'm going to leave this issue open to remind me to add a version number to the output.
