### ISSUE TITLE
process in percent

### ISSUE THREAD

**Issue by badsmoke** [ncabatoff/process-exporter#83]
Hello,

how can I convert the individual process times into percentages?

**Comment by vizdrag561** [comment]
Use Grafana with {{groupnames}} legend
```
(avg by (groupname) (irate(namedprocess_namegroup_cpu_user_seconds_total{job="Processes",instance=~"$instance:9256", groupname=~"$processes"}[$interval])) * 100)
```

**Comment by ncabatoff** [comment]
I think what @badsmoke wants is to know what percent of the total CPU time is being used by each group.  Multiplying by 100 is insufficient unless you have a single core, because we're measuring the consumed core-seconds per seconds.  So for example, if you have 2 cores, and every second group A is consuming one and a half of their available resources as user time, process-exporter will show a rate of 1.5, and when you multiply by 100 that would result in 150% using Grafana's "percent" (1-100) format.

Since process-exporter is never going to be able to capture every process's consumption (think e.g. of very short-lived processes), and you're generally better off being selective rather than trying to monitor every single running process, I recommend that you use node_exporter as well.  Then you can take the ratio of the rate of namedprocess_namegroup_cpu_user_seconds_total to the rate of node_cpu_seconds_total{mode="user"}, or you include the system time in your equation as well, as you see fit.

**Comment by kinhak** [comment]
Hi,
I am still not able to get CPU usage in percentage
I am getting following metrics from prcoess_exporter (multiple instance,multiple processes, multiple instance of single process on each instance)
For ex - 
namedprocess_namegroup_cpu_seconds_total{groupname="bond_process",instance="machine1:9256",job="process_exporter",mode="user"}
namedprocess_namegroup_cpu_seconds_total{groupname="cash_process",instance="machine1:9256",job="process_exporter",mode="user"}
namedprocess_namegroup_cpu_seconds_total{groupname="bond_process",instance="machine2:9256",job="process_exporter",mode="user"}
namedprocess_namegroup_cpu_seconds_total{groupname="cash_process",instance="machine2:9256",job="process_exporter",mode="user"}

I want to get following output
groupname                 instance                      %cpu
bond_process             machine1                      50%
cash_process              machine1                       40%
bond_process             machine2                       12%
cash_process               machine2                       10%

And yes, each machine has 20 cores

Can you please provide me exact formula?

**Comment by geekdave** [comment]
Just in case anyone else comes across this, I was able to get the relative CPU usage per-process compared to overall CPU capacity with this:

```
sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~"$processes",instance=~"$host"}[$interval])) 
/ sum(rate(node_cpu{job="node", instance=~"$host"}[$interval]))
```

Note that I'm using an old version of node_exporter, so for the newer versions you'll want to substitute in node_cpu_seconds_total for node_cpu.

Verified with the `stress` tool on a 2 cpu machine using a 1 core and 2 core test, shown here:

<img width="904" alt="Named_Processes_Multiple_-_Grafana" src="https://user-images.githubusercontent.com/1438478/62171701-19b81b00-b2ed-11e9-9f5d-e064d2d2b81b.png">

**Comment by sk1me** [comment]
Try this query:
`sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~".+"}[5m])) by (groupname) * 100`

**Comment by ethirolle** [comment]
Perhaps unexpectedly, if you do a `rate` or `irate` on the metrics like `node_cpu_seconds_total` (from node_exporter) or `namedprocess_namegroup_cpu_user_seconds_total` (from process_exporter), the resulting numbers are already expressed as ratios. For example, if `namedprocess_namegroup_cpu_user_seconds_total` is 0.013 for a given process, you can just multiply that number by 100 (to convert from ratio to percentage) to see that this process used 1.3% of the CPU. This is because rate & irate always result in a per-second rate, thus the `...cpu_seconds_total` metric will be the fraction of that second used by the given process.

Or maybe [this](https://www.robustperception.io/understanding-machine-cpu-usage/) states it more simply:
> As these values always sum to one second per second for each cpu, the per-second rates are also the ratios of usage.
