### ISSUE TITLE
How to capture custom processes

### ISSUE THREAD

**Issue by vivekbny** [ncabatoff/process-exporter#91]
We need to capture the below custom process running in our server via process-exporter

rbxxxxx    300 31376  0 Apr06 ?        00:13:33 /hwak/apps/2017r2/estar/tpe/servers/msgservice/messagecenter -servicetype=PROCESSOR

rbxxxxx  31497 31376  1 Apr06 ?        00:36:09 /hwak/apps/2017r2/starengine/bin/estareng /hwak/apps/2017r2/starengine/engines/B1A/config/boot.ini

rbxxxxx  32722 31376  0 Apr06 ?        00:22:18 /apps/shared/jre1.8.0_20/bin/java -Xmx512m -XX:-UseParallelGC -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Dlog4j.configuration=hwakjmsbroker-log4j.xml -Dhwakapi.logs.folder=/hwak/apps/2017r2/logs/starweb/hwakjms/default/ -Djna.library.path=/hwak/apps/2017r2/lib -jar hwakapplauncher.jar -hwakappjar hwakjmsbroker.jar -hwakappclass com.hwak.mcjms.hwakJMSBroker -hwakcfgfolder /hwak/apps/2017r2/estar/tpe/cfg/hwakjms/amq -hwaklibfolder /hwak/apps/2017r2/estar/tpe/servers/hwakjms

Below is the yml we use currently, but unable to capture the processes. Can someone please let me know how to configure the yml to capture these processes.

process-selection.yml:

process_names:
  - cmdline:
    - .+

**Comment by ncabatoff** [comment]
Hi @vivekbny,

What do you mean by "unable to capture the processes"?  My guess is their metrics are being captured, but they're falling into namegroups that doesn't make it obvious because you're only using the default naming.  For example, is there a namegroup `java` in your output?  That's probably where hwakjms is being lumped in.  You would probably need a more specific regular expression coupled with a templated name in order to get it in its own group, something along the lines of (untested):

```
process_names:
 - name: "{{.Comm}}:{{.Matches.Jar}}"
   comm:
   - java
   cmdline: 
   - -jar\s+(?P<Jar>.+).jar
```
