### ISSUE TITLE
Add PID to metrics

### ISSUE THREAD

**Issue by domleb** [ncabatoff/process-exporter#98]
I would like to monitor the threads of Nginx so we can alert when worker processes are saturated.  I've enabled `-threads` but because all Nginx threads have the same name (nginx) in field comm(2) from /proc/[pid]/stat, I only get a single timeseries.

Could the PID (first field from proc/[pid]/stat) be added as a label?

**Comment by ncabatoff** [comment]
Hi @domleb,

I don't think using PID as a label is a good idea, because it will result in a lot of churn and high cardinality series, which Prometheus doesn't like.  My plan to address your use case is #62.  If you have any thoughts on that approach please feel free to add them to that issue.  I'm going to close this one as a dup, because I don't plan to implement the solution you're proposing and I think both issues are trying to address the same problem, i.e. that the current breakdown by thread name isn't useful for most programs.
